### ISSUE TITLE
Missing information on c-base presentation at BHNT#2

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin.hackandtell.org#103]
Somebody from c-base ("t" ?) presented "c-base lightcontrol" at 2nd BHNT. Do you have any idea who was it?

Also, the URLs pointing to "dev.c-base.org" no longer exist. Do you have any idea where these were moved to?

**Comment by stefanhoth** [comment]
Ancient questions/projects here. I love it!

The project is likely this one: https://github.com/c-base/dmxdmon
It moved when the internal c-base git space was closed.

The presenter was @yncyrydybyl.

**Comment by vog** [comment]
Reopening this issue, as this information still needs to be incorporated into README.md

**Comment by vog** [comment]
Ok, created pull request for that.
