### ISSUE TITLE
Rename GitHub repository

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin.hackandtell.org#142]
I propose to rename GitHub repository from "berlin-hack-and-tell.github.io" to "berlin.hackandtell.org", and to adjust the link in the project description accordingly.

@stefanhoth @ligi Any objections?

**Comment by ligi** [comment]
I think this might not work anymore then - wasn't it the case that this speciall naming triggers the jekyll processing - or is the config.yml enough? Also we might have some links to the current URL which are broken then - my gut says keep this as it is - but it is not a strong feeling - would not object if you really want to do so

**Comment by vog** [comment]
No, the special naming was only needed as long as we used "berlin-hack-and-tell.github.io".

Every repo can be a Jekyll-site, I do that a lot with my own repos. However, without the special repo name it is served from the sub-URL `https://berlin-hack-and-tell.github.io/REPONAME/`. For example, I have https://vog.github.io/shasplit/ and https://vog.github.io/bitcoinproof/.

In short: Now that we have the subdomain and CNAME file, we can safely rename it.

**Comment by vog** [comment]
Any other objections? @stefanhoth?

**Comment by ligi** [comment]
thanks for the clarification @vog - but still we might get broken links then as https://berlin-hack-and-tell.github.io will not work anymore - perhaps this should get a redirect

**Comment by vog** [comment]
@ligi Agreed. Let's see what the GitHub configuration offers in that regard. It is definitely possible, the question is just what is the easiest way to setup that redirect (either a direct GitHub settings, or a dummy repo with just a CNAME).

@stefanhoth Are you okay with this?

**Comment by stefanhoth** [comment]
If the repo doesn't have that name I think the content needs to move from master to gh-pages as a branch name. Other than that I have no reservations.

**Comment by vog** [comment]
@stefanhoth The gh-pages branch is no longer needed. In the Settings tab you can specify that GitHub-pages shall take the master branch.

(I applauded that change, because I'm a firm believer of "documentation = website" and "documentation should be as close as possible to the source". In the past I always had some mechanism that ensures the gh-pages branch is always identical to master. When GitHub added this setting, I finally didn't need that mechanism anymore.)

**Comment by vog** [comment]
Since there are no further objections, I'm renaming the repo.

**Comment by vog** [comment]
Renaming finished successfully.

To keep the old URL https://berlin-hack-and-tell.github.io working, I unfortunately had to create a "berlin-hack-and-tell.github.io" repository just for the redirect. Maybe this isn't worth the trouble?

@stefanhoth @ligi Should we keep or remove the "berlin-hack-and-tell.github.io" redirect repository?

**Comment by stefanhoth** [comment]
I don't mind having it. Working links are always good 👍

**Comment by vog** [comment]
Okay, so let's keep things as they are.
