### ISSUE TITLE
Missing winners of BHNT#16 and BHNT#17

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlin.hackandtell.org#60]
Does anybody know which presentations became the **Hack of the month** of BHNT#16 and BHNT#17?

**Comment by stefanhoth** [comment]
Sorry, I have no data on this.

**Comment by vog** [comment]
Maybe we could ask around via Meetup who were the winners? However, we risk to receive false positives this way, I guess. ;-)

**Comment by stefanhoth** [comment]
Actually come to think of it we didn't start the "Hack of the Month" with the trophy until the 3rd year or so,I think. Might be that there was no winner.

**Comment by stefanhoth** [comment]
Maybe @kcorwin or @cbuchler know?

**Comment by vog** [comment]
@kcorwin, @cbuchler: Do you have any information on this?

**Comment by cbuchler** [comment]
@vog I'm sorry, I don't :-(

**Comment by kcorwin** [comment]
To the message boards!

16:
https://www.meetup.com/Berlin-Hack-and-Tell/boards/view/viewthread?thread=28315082
> Our winner: CSS3 Animations by Maryna

17:
Not actually documented, but I'm pretty sure the winner was some guy named @stefanhoth --
https://www.meetup.com/Berlin-Hack-and-Tell/messages/boards/thread/29525742

**Comment by vog** [comment]
16:

I must have overlooked this. Thanks! See PR #143

17:

@stefanhoth: Can you confirm this?

**Comment by stefanhoth** [comment]
It's true. Who won #17 and neverever again? Oh yeah...

![](https://media.giphy.com/media/3o7TKRdui2W7eOQ99K/source.gif)
